version: "2"
volumes:
  go:

services:
  redis:
    image: redis

  app:
    build:
      context: ""
    command: "go run main.go server -r redis://redis:6379"
    depends_on:
      - redis
    links:
      - redis:redis
    volumes:
    - go:/go
    - $PWD:/usr/src/app
    tty: true
    ports:
    - 8000:8000
